### ISSUE TITLE
如果不知道ImageToData.py为什么运行不起来的话

### ISSUE THREAD

**Issue by Tinhone** [AcosX/Luogu-paintboard-new#2]
[python运行py文件的几种方法 - 百度经验](https://baidu.physton.com/?q=python%E8%BF%90%E8%A1%8Cpy%E6%96%87%E4%BB%B6%E7%9A%84%E5%87%A0%E7%A7%8D%E6%96%B9%E6%B3%95%20-%20%E7%99%BE%E5%BA%A6%E7%BB%8F%E9%AA%8C)

作为一个没有配置环境变量的蒟蒻，当时没运行起来的时候完全是懵逼的

**Comment by AcosX** [comment]
Python安装的时候应该就有“Add Python 3.x to PATH”的选项吧

**Comment by Tinhone** [comment]
用VS装的话好像选不了

**Comment by AcosX** [comment]
哦这样吗......我是从官网安装的......
