### ISSUE TITLE
关于删除daemon=True

### ISSUE THREAD

**Issue by YuzhenQin** [AcosX/Luogu-paintboard-new#8]
为什么要删除呢  
删除可能导致用户无法使用 Ctrl+C 强制结束程序

**Comment by AcosX** [comment]
感觉从逻辑上绘图的线程没道理作为守护线程...
我这边测试Ctrl + C正常
![image](https://user-images.githubusercontent.com/46348773/147869957-1df0e394-b070-4087-bad3-e9b1e43df0fb.png)

**Comment by AcosX** [comment]
有问题吗？有问题的话请告诉我，我加上好了
